
# Site settings

# Setup
title:            Writegood
url:              http://yoomee.github.io/writegood

author:
  name:           'Writegood'
  url:            http://writegood.com

# Custom vars
version:          1.0.0

github:
  repo:           ''
baseurl:          '/team-storytelling'
